  const testsData = [
            

       
  
  { id: 1, name: "هيموجلوبين (Hb%) - Hemoglobin", category: "hematology", specimen: "EDTA", time: "1 يوم", price: 50, conditions: "" },
  { id: 2, name: "تحليل صورة دم كاملة (CBC) - Complete Blood Count", category: "hematology", specimen: "EDTA", time: "1 يوم", price: 150, conditions: "" },
  { id: 3, name: "معدل ترسيب كرات الدم الحمراء (ESR) - Erythrocyte Sedimentation Rate", category: "hematology", specimen: "ESR Tube", time: "1 يوم", price: 70, conditions: "" },
  { id: 4, name: "الخلايا الشبكية (Retics) - Reticulocytes", category: "hematology", specimen: "EDTA", time: "1 يوم", price: 100, conditions: "" },
  { id: 5, name: "فصيلة الدم (ABO) - Blood Group", category: "hematology", specimen: "EDTA", time: "1 يوم", price: 50, conditions: "" },
  { id: 6, name: "عامل ريسس (RH) - Rhesus Factor", category: "hematology", specimen: "EDTA", time: "1 يوم", price: 50, conditions: "" },
  { id: 7, name: "هيموجلوبين إلكتروفوريسيس (Hb Electrophoresis) - Hemoglobin Electrophoresis", category: "hematology", specimen: "EDTA", time: "3 أيام", price: 320, conditions: "" },
  { id: 8, name: "نقص إنزيم G6PD (G6PD) - Glucose-6-Phosphate Dehydrogenase", category: "hematology", specimen: "EDTA", time: "1 يوم", price: 200, conditions: "أنيميا الفول - عدم نقل دم قبل 2 يوم" },
  { id: 9, name: "فيريتين (S. Ferritin) - Ferritin", category: "iron profile", specimen: "Serum", time: "1 يوم", price: 200, conditions: "" },
  { id: 10, name: "حديد (S. Iron) - Iron", category: "iron profile", specimen: "Serum", time: "1 يوم", price: 130, conditions: "" },
  { id: 11, name: "القدرة الكلية على ارتباط الحديد (TIBC) - Total Iron Binding Capacity", category: "iron profile", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 12, name: "القدرة غير المشبعة على ارتباط الحديد (UIBC) - Unsaturated Iron Binding Capacity", category: "iron profile", specimen: "Serum", time: "1 يوم", price: 50, conditions: "محسوب" },
  { id: 13, name: "نسبة تشبع الترانسفيرين (Transferrin Saturation) - Transferrin Saturation", category: "iron profile", specimen: "Serum", time: "1 يوم", price: 50, conditions: "محسوب" },
  { id: 14, name: "ترانسفيرين (Transferrin) - Transferrin", category: "iron profile", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 15, name: "مستقبلات الترانسفيرين الذائبة (Soluble transferrin receptor) - Soluble Transferrin Receptor", category: "iron profile", specimen: "Serum", time: "6 أيام", price: 250, conditions: "" },
  { id: 16, name: "ترانسفيرين في البراز (Transferrin in Stool) - Transferrin in Stool", category: "iron profile", specimen: "Stool", time: "1 يوم", price: 400, conditions: "التأكد من توفره من الفرع" },
  { id: 17, name: "ترانسفيرين في البول (Transferrin in urine) - Transferrin in Urine", category: "iron profile", specimen: "Urine", time: "1 يوم", price: 200, conditions: "التأكد من توفره من الفرع" },
  { id: 18, name: "سكر صائم (F.B.S) - Fasting Blood Sugar", category: "blood sugar", specimen: "Sod. florid", time: "1 يوم", price: 35, conditions: "صيام 8 إلى 10 ساعات" },
  { id: 19, name: "سكر بعد الأكل بساعتين (PP.B.S) - Postprandial Blood Sugar", category: "blood sugar", specimen: "Sod. florid", time: "1 يوم", price: 35, conditions: "بعد الأكل بساعتين" },
  { id: 20, name: "سكر عشوائي (R.B.S) - Random Blood Sugar", category: "blood sugar", specimen: "Sod. florid", time: "1 يوم", price: 35, conditions: "بدون صيام" },
  { id: 21, name: "الهيموجلوبين السكري (HbA1C) - Glycated Hemoglobin", category: "blood sugar", specimen: "Blood EDTA", time: "1 يوم", price: 170, conditions: "بدون صيام" },
  { id: 22, name: "مقاومة الأنسولين (HOMA-IR) - Homeostatic Model Assessment for Insulin Resistance", category: "blood sugar", specimen: "Serum + Sod. florid", time: "1 يوم", price: 250, conditions: "صيام 8 إلى 10 ساعات" },
  { id: 23, name: "أنسولين صائم (Insulin Fasting) - Fasting Insulin", category: "blood sugar", specimen: "Frozen Serum", time: "1 يوم", price: 180, conditions: "صيام 8 إلى 10 ساعات" },
  { id: 24, name: "أنسولين بعد الأكل (Insulin (P.P)) - Postprandial Insulin", category: "blood sugar", specimen: "Frozen Serum", time: "1 يوم", price: 180, conditions: "بعد الأكل بساعتين" },
  { id: 25, name: "أنسولين عشوائي (Insulin (Random)) - Random Insulin", category: "blood sugar", specimen: "Frozen Serum", time: "1 يوم", price: 180, conditions: "بدون صيام" },
  { id: 26, name: "سي بيبتيد صائم (C – Peptide (Fasting)) - C-Peptide Fasting", category: "blood sugar", specimen: "Frozen Serum", time: "1 يوم", price: 250, conditions: "صيام 8 إلى 10 ساعات" },
  { id: 27, name: "سي بيبتيد بعد الأكل (C – Peptide (P.P)) - C-Peptide Postprandial", category: "blood sugar", specimen: "Frozen Serum", time: "1 يوم", price: 250, conditions: "بعد الأكل بساعتين" },
  { id: 28, name: "إنزيم AST (S.GOT) - Aspartate Aminotransferase", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 70, conditions: "" },
  { id: 29, name: "إنزيم ALT (S.GPT) - Alanine Aminotransferase", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 70, conditions: "" },
  { id: 30, name: "بيليروبين كلي (Total Bilirubin) - Total Bilirubin", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 31, name: "بيليروبين مباشر (Direct Bilirubin) - Direct Bilirubin", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 32, name: "إنزيم الفوسفاتاز القلوي (Alk – Phosphatase) - Alkaline Phosphatase", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 80, conditions: "" },
  { id: 33, name: "ألبومين (Albumin) - Albumin", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 80, conditions: "" },
  { id: 34, name: "بروتين كلي (Total Protein) - Total Protein", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 80, conditions: "" },
  { id: 35, name: "إنزيم GGT (Gamma GT) - Gamma-Glutamyl Transferase", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 80, conditions: "" },
  { id: 36, name: "جلوبيولين (Globulin) - Globulin", category: "liver profile", specimen: "Serum", time: "1 يوم", price: 80, conditions: "" },
  { id: 37, name: "يوريا (Urea - BUN) - Urea", category: "kidney function", specimen: "Serum", time: "1 يوم", price: 70, conditions: "" },
  { id: 38, name: "كرياتينين (Creat) - Creatinine", category: "kidney function", specimen: "Serum", time: "1 يوم", price: 70, conditions: "" },
  { id: 39, name: "معدل الترشيح الكبيبي (e-GFR) - Estimated Glomerular Filtration Rate", category: "kidney function", specimen: "Serum", time: "1 يوم", price: 70, conditions: "محسوب من الكرياتينين" },
  { id: 40, name: "حمض اليوريك (Uric Acid (U.A)) - Uric Acid", category: "kidney function", specimen: "Serum", time: "1 يوم", price: 70, conditions: "" },
  { id: 41, name: "نسبة الكالسيوم إلى الكرياتينين في البول (Calcium/Creatinine Ratio) - Calcium/Creatinine Ratio", category: "kidney function", specimen: "Urine Sample After 2 h Fasting", time: "1 يوم", price: 200, conditions: "" },
  { id: 42, name: "نسبة البروتين إلى الكرياتينين في البول (Protein / Creatinine Ratio) - Protein/Creatinine Ratio", category: "kidney function", specimen: "1 ml Morning Urine", time: "1 يوم", price: 200, conditions: "ثاني عينة بول صباحية" },
  { id: 43, name: "نسبة الألبومين إلى الكرياتينين في البول (Albumin / Creatinine Ratio) - Albumin/Creatinine Ratio", category: "kidney function", specimen: "Random Urine Sample", time: "1 يوم", price: 200, conditions: "" },
  { id: 44, name: "نسبة حمض اليوريك إلى الكرياتينين في البول (Uric Acid /Creatinine Ratio) - Uric Acid/Creatinine Ratio", category: "kidney function", specimen: "1 ml Morning Urine", time: "1 يوم", price: 200, conditions: "" },
  { id: 45, name: "مايكرو ألبومين في البول (Micro – albumin in urine) - Microalbumin in Urine", category: "kidney function", specimen: "Random Urine Sample", time: "1 يوم", price: 200, conditions: "ثاني عينة بول صباحية" },
  { id: 46, name: "تصفية الكرياتينين (Creratinine Clearance) - Creatinine Clearance", category: "kidney function", specimen: "Serum + 24 h Urine Collected", time: "1 يوم", price: 200, conditions: "مطلوب الوزن" },
  { id: 47, name: "بروتين في البول (Protein in Urine) - Protein in Urine", category: "kidney function", specimen: "24 h urine collection Or Random Sample", time: "1 يوم", price: 100, conditions: "" },
  { id: 48, name: "بروتين كلي (Total Protein) - Total Protein", category: "kidney function", specimen: "Serum", time: "1 يوم", price: 70, conditions: "" },
  { id: 49, name: "ملف الدهون (Lipid Profile) - Lipid Profile", category: "lipid profile", specimen: "Blood EDTA", time: "1 يوم", price: 280, conditions: "صيام 10 إلى 12 ساعة" },
  { id: 50, name: "كوليسترول (Cholesterol) - Cholesterol", category: "lipid profile", specimen: "Serum", time: "1 يوم", price: 70, conditions: "لا يحتاج صيام" },
  { id: 51, name: "دهون ثلاثية (Tri Glesrides) - Triglycerides", category: "lipid profile", specimen: "Serum", time: "1 يوم", price: 70, conditions: "صيام 10 إلى 12 ساعة" },
  { id: 52, name: "كوليسترول HDL (HDL) - High-Density Lipoprotein", category: "lipid profile", specimen: "Serum", time: "1 يوم", price: 70, conditions: "صيام 10 إلى 12 ساعة" },
  { id: 53, name: "كوليسترول LDL (LDL) - Low-Density Lipoprotein", category: "lipid profile", specimen: "Serum", time: "1 يوم", price: 70, conditions: "صيام 10 إلى 12 ساعة" },
  { id: 54, name: "تحليل بول (Urine Analysis) - Urine Analysis", category: "parasitology", specimen: "Urine sample", time: "1 يوم", price: 45, conditions: "" },
  { id: 55, name: "تحليل براز (Stool Analysis) - Stool Analysis", category: "parasitology", specimen: "Stool Sample", time: "1 يوم", price: 45, conditions: "" },
  { id: 56, name: "مزرعة بول (Urine Culture) - Urine Culture", category: "culture & sensitivity", specimen: "Urine", time: "3-4 أيام", price: 250, conditions: "الامتناع عن المضاد الحيوي 3 أيام" },
  { id: 57, name: "مزرعة براز (Stool Culture) - Stool Culture", category: "culture & sensitivity", specimen: "Stool", time: "3-4 أيام", price: 250, conditions: "الامتناع عن المضاد الحيوي 3 أيام" },
  { id: 58, name: "مزرعة مسحة مهبلية (Vaginal Swab C/S) - Vaginal Swab Culture", category: "culture & sensitivity", specimen: "", time: "3-4 أيام", price: 250, conditions: "الامتناع عن المضاد الحيوي 3 أيام" },
  { id: 59, name: "مزرعة فطريات (Fungus Culture) - Fungus Culture", category: "culture & sensitivity", specimen: "", time: "3-4 أيام", price: 250, conditions: "الامتناع عن المضاد الحيوي 3 أيام" },
  { id: 60, name: "مزرعة مسحة حلق (Throat Swab C/S) - Throat Swab Culture", category: "culture & sensitivity", specimen: "", time: "3-4 أيام", price: 250, conditions: "الامتناع عن المضاد الحيوي 3 أيام" },
  { id: 61, name: "مزرعة دم (Blood Culture) - Blood Culture", category: "culture & sensitivity", specimen: "", time: "10 أيام", price: 400, conditions: "توضع عينة الدم مباشرة 10 cm في الزجاجة الخاصة بمزرعة الدم" },
  { id: 62, name: "مزرعة فطريات (Fungus Culture) - Fungus Culture", category: "culture & sensitivity", specimen: "عينه من الظافر او اي عينه يحددها الدكتور", time: "21 يوم", price: 250, conditions: "" },
  { id: 63, name: "فحص KOH (KOH Examination) - Potassium Hydroxide Test", category: "parasitology", specimen: "عينه من الظافر او اي عينه يحددها الدكتور", time: "2 يوم", price: 170, conditions: "" },
  { id: 64, name: "كالسيوم كلي (Ca-Total) - Total Calcium", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 70, conditions: "" },
  { id: 65, name: "كالسيوم متأين (Ca-Ionized (Ca++)) - Ionized Calcium", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 80, conditions: "" },
  { id: 66, name: "ماغنيسيوم (Magnesium (Mg)) - Magnesium", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 67, name: "صوديوم (Sodium (Na)) - Sodium", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 68, name: "بوتاسيوم (Potassium (K)) - Potassium", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 69, name: "حديد (S.Iron (Fe)) - Iron", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 130, conditions: "" },
  { id: 70, name: "فوسفور (Phosphorus (P)) - Phosphorus", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 71, name: "نحاس (Copper (Cu)) - Copper", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 200, conditions: "" },
  { id: 72, name: "زنك (Zink (Zn)) - Zinc", category: "electrolytes", specimen: "Serum", time: "1 يوم", price: 220, conditions: "" },
  { id: 73, name: "هرمون T3 (T3) - Triiodothyronine", category: "hormones", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 74, name: "هرمون T4 (T4) - Thyroxine", category: "hormones", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 75, name: "هرمون T3 الحر (F. T3) - Free Triiodothyronine", category: "hormones", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 76, name: "هرمون T4 الحر (F .T4) - Free Thyroxine", category: "hormones", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 77, name: "هرمون TSH (TSH) - Thyroid Stimulating Hormone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 78, name: "أجسام مضادة للغدة الدرقية (Thyroid Ab) - Thyroid Antibodies", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 79, name: "أجسام مضادة للميكروسومات (Anti-Microsomal Ab (TPO)) - Anti-Thyroid Peroxidase Antibodies", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 80, name: "أجسام مضادة للغدة الدرقية (Anti Thyroid Ab) - Anti-Thyroid Antibodies", category: "hormones", specimen: "Serum", time: "1 يوم", price: 270, conditions: "" },
  { id: 81, name: "أجسام مضادة للثايروجلوبيولين (Anti-Thyroglobulin Ab. (ATG)) - Anti-Thyroglobulin Antibodies", category: "hormones", specimen: "Serum", time: "1 يوم", price: 270, conditions: "" },
  { id: 82, name: "ثايروجلوبيولين (Thyroglobulin) - Thyroglobulin", category: "hormones", specimen: "Serum", time: "1 يوم", price: 500, conditions: "" },
  { id: 83, name: "اختبار حمل (Pregnancy Test) - Pregnancy Test", category: "hormones", specimen: "Serum", time: "1 يوم", price: 60, conditions: "" },
  { id: 84, name: "هرمون الحمل النوعي (B-HCG (Qualitative)) - Qualitative Beta hCG", category: "hormones", specimen: "Serum", time: "1 يوم", price: 60, conditions: "" },
  { id: 85, name: "هرمون الحمل الكمي (B- HCG (Quantitative)) - Quantitative Beta hCG", category: "hormones", specimen: "Serum", time: "1 يوم", price: 170, conditions: "" },
  { id: 86, name: "هرمون FSH (FSH) - Follicle Stimulating Hormone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 220, conditions: "" },
  { id: 87, name: "هرمون LH (LH) - Luteinizing Hormone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 170, conditions: "" },
  { id: 88, name: "هرمون الحليب (Prolactin (PRL)) - Prolactin", category: "hormones", specimen: "Serum", time: "1 يوم", price: 170, conditions: "" },
  { id: 89, name: "هرمون AMH (AMH (Anti-Mullerian Hormone)) - Anti-Mullerian Hormone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 550, conditions: "" },
  { id: 90, name: "هرمون DHEA (DHEA) - Dehydroepiandrosterone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 91, name: "هرمون DHEA-S (DHEA S) - Dehydroepiandrosterone Sulfate", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 92, name: "هرمون البروجسترون (Progesterone) - Progesterone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 93, name: "هرمون التستوستيرون الكلي (Testosterone Total) - Total Testosterone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 94, name: "هرمون التستوستيرون الحر (Testosterone Free) - Free Testosterone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 200, conditions: "" },
  { id: 95, name: "هرمون الاستراديول (Estradiol (E2)) - Estradiol", category: "hormones", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 96, name: "هرمون الاستريول (Estriol (E3)) - Estriol", category: "hormones", specimen: "Serum", time: "1 يوم", price: 500, conditions: "" },
  { id: 97, name: "هرمون الغدة الجار درقية (Para thyroid Hormone (PTH)) - Parathyroid Hormone", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 98, name: "كورتيزول صباحي (Cortisol (AM)) - Morning Cortisol", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "تسحب العينة الساعة 8 إلى 9 صباحا" },
  { id: 99, name: "كورتيزول مسائي (Cortisol (Pm)) - Evening Cortisol", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "تسحب العينة بين 8 إلى 9 مساءا" },
  { id: 100, name: "كورتيزول عشوائي (Cortisol Random) - Random Cortisol", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "عينة عشوائية" },
  { id: 101, name: "هرمون ACTH صباحي (ACTH (AM)) - Morning Adrenocorticotropic Hormone", category: "hormones", specimen: "EDTA", time: "1 يوم", price: 250, conditions: "تسحب العينة الساعة 8 إلى 9 صباحا" },
  { id: 102, name: "هرمون ACTH مسائي (ACTH (PM)) - Evening Adrenocorticotropic Hormone", category: "hormones", specimen: "EDTA", time: "1 يوم", price: 250, conditions: "تسحب العينة بين 8 إلى 9 مساءا" },
  { id: 103, name: "هرمون النمو الأساسي (GH - Basal (Growth hormone Basal)) - Growth Hormone Basal", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "تسحب العينة الساعة 8 صباحا - صيام 10 إلى 12 ساعة" },
  { id: 104, name: "هرمون النمو بعد التحفيز بالتمارين (GH (Growth hormone After Stimulation by Exercise)) - Growth Hormone Post-Exercise", category: "hormones", specimen: "Serum", time: "1 يوم", price: 250, conditions: "تسحب العينة بعد التمارين" },
  { id: 105, name: "بكتيريا H. pylori في البراز (H- Pylori Ag in Stool) - Helicobacter pylori Antigen in Stool", category: "serology", specimen: "Stool", time: "1 يوم", price: 170, conditions: "" },
  { id: 106, name: "بكتيريا H. pylori في البراز (H-Pylori Ag Stool (Titer)) - Helicobacter pylori Antigen Titer in Stool", category: "serology", specimen: "Stool", time: "1 يوم", price: 220, conditions: "" },
  { id: 107, name: "أجسام مضادة لـ H. pylori في الدم (H- Pylori Ab in Blood) - Helicobacter pylori Antibodies in Blood", category: "serology", specimen: "Serum", time: "1 يوم", price: 170, conditions: "" },
  { id: 108, name: "كالبروتكتين (Calprotectin) - Calprotectin", category: "serology", specimen: "Stool", time: "3 أيام", price: 550, conditions: "" },
  { id: 109, name: "اختبار وايدال (Widal Test) - Widal Test", category: "serology", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 110, name: "اختبار البروسيلا (Brucella (Latex-Titer)) - Brucella Latex Agglutination Test", category: "serology", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 111, name: "أجسام مضادة للبروسيلا IgG (Brucella (IgG)) - Brucella IgG Antibodies", category: "serology", specimen: "Serum", time: "7 أيام", price: 400, conditions: "" },
  { id: 112, name: "أجسام مضادة للبروسيلا IgM (Brucella IgM) - Brucella IgM Antibodies", category: "serology", specimen: "Serum", time: "7 أيام", price: 400, conditions: "" },
  { id: 113, name: "اختبار روز والر (Rose Waller) - Rose-Waller Test", category: "serology", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 114, name: "فحص TORCH شامل (TORCH Screen) - TORCH Screen", category: "serology", specimen: "Serum", time: "1 يوم", price: 1400, conditions: "" },
  { id: 115, name: "فحص TORCH (IgG + IgM) - TORCH IgG and IgM", category: "serology", specimen: "Serum", time: "1 يوم", price: 1400, conditions: "" },
  { id: 116, name: "فحص TORCH (IgG) - TORCH IgG", category: "serology", specimen: "Serum", time: "1 يوم", price: 700, conditions: "" },
  { id: 117, name: "فحص TORCH (IgM) - TORCH IgM", category: "serology", specimen: "Serum", time: "1 يوم", price: 700, conditions: "" },
  { id: 118, name: "أجسام مضادة للتوكسوبلازما IgM (Toxoplasmosis Ab IgM) - Toxoplasmosis IgM Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 119, name: "أجسام مضادة للتوكسوبلازما IgG (Toxoplasmosis Ab IgG) - Toxoplasmosis IgG Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 120, name: "أجسام مضادة للحصبة الألمانية IgM (Rubella Ab IgM) - Rubella IgM Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 121, name: "أجسام مضادة للحصبة الألمانية IgG (Rubella Ab IgG) - Rubella IgG Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 122, name: "أجسام مضادة للفيروس المضخم للخلايا IgM (Cytomegalovirus Ab IgM (CMV – IgM)) - Cytomegalovirus IgM Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 123, name: "أجسام مضادة للفيروس المضخم للخلايا IgG (Cytomegalovirus Ab IgG (CMV – IgG)) - Cytomegalovirus IgG Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 124, name: "أجسام مضادة لفيروس الهربس النوع الأول IgM (Herpes Virus Ab (I) IgM HSV I (IgM)) - Herpes Simplex Virus Type 1 IgM Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 125, name: "أجسام مضادة لفيروس الهربس النوع الأول IgG (Herpes Virus Ab (I) IgG HSV I (IgG)) - Herpes Simplex Virus Type 1 IgG Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 126, name: "أجسام مضادة لفيروس الهربس النوع الثاني IgM (Herpes Virus Ab (II) IgM HSV II (IgM)) - Herpes Simplex Virus Type 2 IgM Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 127, name: "أجسام مضادة لفيروس الهربس النوع الثاني IgG (Herpes Virus Ab (II) IgG HSV I (IgM)) - Herpes Simplex Virus Type 2 IgG Antibodies", category: "serology", specimen: "Serum", time: "1 يوم", price: 175, conditions: "" },
  { id: 128, name: "إنزيم CPK كلي (CPK Total) - Creatine Phosphokinase Total", category: "cardiac", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 129, name: "إنزيم CK-MB (CK – MB) - Creatine Kinase MB", category: "cardiac", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 130, name: "إنزيم LDH (LDH) - Lactate Dehydrogenase", category: "cardiac", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 131, name: "تروبونين T كمي (Troponin – T(Quantitative)) - Troponin T Quantitative", category: "cardiac", specimen: "Serum", time: "6 أيام", price: 450, conditions: "" },
  { id: 132, name: "تروبونين I نوعي (Troponin – I (Qualitative)) - Troponin I Qualitative", category: "cardiac", specimen: "Serum", time: "1 يوم", price: 200, conditions: "" },
  { id: 133, name: "زمن البروثرومبين (PT - INR) - Prothrombin Time", category: "coagulation", specimen: "Citrated Plasma", time: "1 يوم", price: 100, conditions: "" },
  { id: 134, name: "زمن الثرومبوبلاستين الجزئي (PTT) - Partial Thromboplastin Time", category: "coagulation", specimen: "Citrated Plasma", time: "1 يوم", price: 100, conditions: "" },
  { id: 135, name: "زمن النزيف (Bleeding Time (B.T)) - Bleeding Time", category: "coagulation", specimen: "One drop Blood on slide", time: "1 يوم", price: 60, conditions: "" },
  { id: 136, name: "زمن التجلط (Clotting Time (C.T)) - Clotting Time", category: "coagulation", specimen: "One drop Blood on slide", time: "1 يوم", price: 60, conditions: "" },
  { id: 137, name: "داي دايمر (D-Dimer) - D-Dimer", category: "coagulation", specimen: "Citrated Plasma", time: "1 يوم", price: 250, conditions: "" },
  { id: 138, name: "فيتامين D3 (Vit D3) - Vitamin D3", category: "vitamins", specimen: "Serum", time: "1 يوم", price: 450, conditions: "" },
  { id: 139, name: "فيتامين D (Vit D) - Vitamin D", category: "vitamins", specimen: "Serum", time: "1 يوم", price: 500, conditions: "" },
  { id: 140, name: "فيتامين B12 (Vit B 12) - Vitamin B12", category: "vitamins", specimen: "Serum", time: "1 يوم", price: 450, conditions: "" },
  { id: 141, name: "مستضد البروستاتا النوعي الكلي (PSA Total) - Prostate-Specific Antigen Total", category: "tumor marker", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 142, name: "مستضد البروستاتا النوعي الحر (Free PSA) - Free Prostate-Specific Antigen", category: "tumor marker", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 143, name: "ألفا فيتو بروتين (Alpha Feto Protein (AFP)) - Alpha-Fetoprotein", category: "tumor marker", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 144, name: "مستضد سرطاني مضغي (CEA) - Carcinoembryonic Antigen", category: "tumor marker", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 145, name: "مستضد CA 15.3 (CA 15.3) - Cancer Antigen 15-3", category: "tumor marker", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 146, name: "مستضد CA 19.9 (CA 19.9) - Cancer Antigen 19-9", category: "tumor marker", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 147, name: "مستضد CA 125 (CA 125) - Cancer Antigen 125", category: "tumor marker", specimen: "Serum", time: "1 يوم", price: 250, conditions: "" },
  { id: 148, name: "مستضد CA 72.4 (CA 72.4) - Cancer Antigen 72-4", category: "tumor marker", specimen: "Serum", time: "8 أيام", price: 900, conditions: "" },
  { id: 149, name: "مستضد CA 242 (CA 242) - Cancer Antigen 242", category: "tumor marker", specimen: "Serum", time: "8 أيام", price: 700, conditions: "" },
  { id: 150, name: "مستضد CA 50 (CA 50) - Cancer Antigen 50", category: "tumor marker", specimen: "Serum", time: "8 أيام", price: 1200, conditions: "" },
  { id: 151, name: "أجسام مضادة لفيروس سي (HCV Ab) - Hepatitis C Virus Antibodies", category: "virology", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 152, name: "مستضد سطحى لفيروس بي (HBs Ag) - Hepatitis B Surface Antigen", category: "virology", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 153, name: "أجسام مضادة لفيروس بي (HBs Ab) - Hepatitis B Surface Antibodies", category: "virology", specimen: "Serum", time: "1 يوم", price: 200, conditions: "" },
  { id: 154, name: "أجسام مضادة لفيروس نقص المناعة البشرية (HIV Ab) - Human Immunodeficiency Virus Antibodies", category: "virology", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 155, name: "أجسام مضادة لفيروس أ IgG (HAV – Ab (IgG)) - Hepatitis A Virus IgG Antibodies", category: "virology", specimen: "serum", time: "1 يوم", price: 200, conditions: "" },
  { id: 156, name: "أجسام مضادة لفيروس أ IgM (HAV – IgM) - Hepatitis A Virus IgM Antibodies", category: "virology", specimen: "serum", time: "1 يوم", price: 200, conditions: "" },
  { id: 157, name: "PCR لفيروس سي كمي (HCV PCR Quantitative) - Hepatitis C Virus PCR Quantitative", category: "virology", specimen: "EDTA Plasma", time: "2 يوم", price: 450, conditions: "" },
  { id: 158, name: "أجسام مضادة لفيروس سي IgM (HCV IgM) - Hepatitis C Virus IgM Antibodies", category: "virology", specimen: "Serum", time: "5-6 أيام", price: 450, conditions: "" },
  { id: 159, name: "تحديد نوع فيروس سي (HCV Genotyping) - Hepatitis C Virus Genotyping", category: "virology", specimen: "serum", time: "7-8 أيام", price: 1600, conditions: "" },
  { id: 160, name: "PCR لفيروس بي كمي (HBV PCR Quantitative) - Hepatitis B Virus PCR Quantitative", category: "virology", specimen: "EDTA Plasma", time: "2 يوم", price: 500, conditions: "" },
  { id: 161, name: "تحديد نوع فيروس بي (HBV Genotyping) - Hepatitis B Virus Genotyping", category: "virology", specimen: "EDTA Plasma", time: "7-8 أيام", price: 1400, conditions: "" },
  { id: 162, name: "PCR لفيروس نقص المناعة البشرية كمي (HIV-RNA by PCR (Quantative)) - Human Immunodeficiency Virus RNA PCR Quantitative", category: "virology", specimen: "EDTA Plasma", time: "7 أيام", price: 900, conditions: "" },
  { id: 163, name: "PCR لفيروس نقص المناعة البشرية نوعي (HIV PCR Qualitative) - Human Immunodeficiency Virus PCR Qualitative", category: "virology", specimen: "EDTA Plasma", time: "7 أيام", price: 1200, conditions: "" },
  { id: 164, name: "مستضد فيروس الروتا (Rotavirus Antigen) - Rotavirus Antigen", category: "virology", specimen: "Stool Sample", time: "1 يوم", price: 300, conditions: "" },
  { id: 165, name: "بروتين سي التفاعلي (CRP) - C-Reactive Protein", category: "immunology", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 166, name: "مضادات الستربتوليزين O (ASO-T) - Anti-Streptolysin O Titer", category: "immunology", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 167, name: "عامل الروماتويد (Rheumatoid Factor (RF)) - Rheumatoid Factor", category: "immunology", specimen: "Serum", time: "1 يوم", price: 100, conditions: "" },
  { id: 168, name: "أجسام مضادة للببتيد السيتروليني الحلقي (Anti CCP) - Anti-Cyclic Citrullinated Peptide", category: "immunology", specimen: "Serum", time: "1 يوم", price: 400, conditions: "" },
  { id: 169, name: "أجسام مضادة للنواة (ANA – Elisa) - Anti-Nuclear Antibodies ELISA", category: "immunology", specimen: "Serum", time: "1 يوم", price: 270, conditions: "" },
  { id: 170, name: "أجسام مضادة للنواة (Anti -Nuclear Abs - Elisa) - Anti-Nuclear Antibodies ELISA", category: "immunology", specimen: "Serum", time: "3-4 أيام", price: 420, conditions: "" },
  { id: 171, name: "أجسام مضادة للنواة (ANA – ( IF )) - Anti-Nuclear Antibodies Immunofluorescence", category: "immunology", specimen: "Serum", time: "3-4 أيام", price: 650, conditions: "" },
  { id: 172, name: "أجسام مضادة للنواة (ANA – ( IF ) titre) - Anti-Nuclear Antibodies Immunofluorescence Titer", category: "immunology", specimen: "Serum", time: "1 يوم", price: 270, conditions: "" },
  { id: 173, name: "أجسام مضادة للـ DNA (DNA (Anti-DNA (d.s) (ELISA)) - Anti-dsDNA Antibodies ELISA", category: "immunology", specimen: "Serum", time: "3 أيام", price: 420, conditions: "" },
  { id: 174, name: "أجسام مضادة للـ DNA (DNA (Anti-DNA (d.s) (IF)) - Anti-dsDNA Antibodies Immunofluorescence", category: "immunology", specimen: "Serum", time: "5-6 أيام", price: 500, conditions: "" },
  { id: 175, name: "أجسام مضادة للـ DNA (DNA (Anti-DNA (d.s) (IF) Titre) - Anti-dsDNA Antibodies Immunofluorescence Titer", category: "immunology", specimen: "Serum", time: "3 أيام", price: 450, conditions: "" },
  { id: 176, name: "أجسام مضادة لـ SS-B/La (Anti-ss-B/La) - Anti-SS-B/La Antibodies", category: "immunology", specimen: "Serum", time: "3 أيام", price: 450, conditions: "" },
  { id: 177, name: "أجسام مضادة لـ SS-A/Ro (Anti-ss-A/Ro) - Anti-SS-A/Ro Antibodies", category: "immunology", specimen: "Serum", time: "3 أيام", price: 450, conditions: "" },
  { id: 178, name: "أجسام مضادة للميتوكوندريا (AMA (Anti Mitochondrial Abs)) - Anti-Mitochondrial Antibodies", category: "immunology", specimen: "Serum", time: "3 أيام", price: 550, conditions: "" },
  { id: 179, name: "أجسام مضادة للعضلات الملساء (ASMA (Anti-Smooth Muscle Antibody)) - Anti-Smooth Muscle Antibodies", category: "immunology", specimen: "Serum", time: "3-4 أيام", price: 350, conditions: "" },
  { id: 180, name: "جلوبيولين مناعي E (IgE (Total)) - Total Immunoglobulin E", category: "immunology", specimen: "Serum", time: "1 يوم", price: 200, conditions: "" },
  { id: 181, name: "تحليل متابعة الأدوية (Drug Monitoring) - Drug Monitoring", category: "others", specimen: "Random Urine Sample", time: "1 يوم", price: 350, conditions: "" },
  { id: 182, name: "كحول في الدم (Alcohol in Blood) - Alcohol in Blood", category: "others", specimen: "Serum", time: "5-6 أيام", price: 450, conditions: "" },
  { id: 183, name: "كحول في البول (Alcohol in urine) - Alcohol in Urine", category: "others", specimen: "Serum", time: "5-6 أيام", price: 450, conditions: "" },
  { id: 184, name: "كحول كمي (Alcohol (Quantitative)) - Alcohol Quantitative", category: "others", specimen: "Serum or Random Urine Sample", time: "5-6 أيام", price: 450, conditions: "" },
  { id: 185, name: "أميلاز في الدم (Amylase in Serum) - Amylase in Serum", category: "others", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 186, name: "أميلاز في البول (Amylase in urine) - Amylase in Urine", category: "others", specimen: "urine", time: "5-6 أيام", price: 150, conditions: "" },
  { id: 187, name: "ليباز (Lipase) - Lipase", category: "others", specimen: "Serum", time: "1 يوم", price: 150, conditions: "" },
  { id: 188, name: "دم خفي في البراز (Occult Blood in Stool) - Occult Blood in Stool", category: "others", specimen: "Stool", time: "1 يوم", price: 170, conditions: "الامتناع عن أدوية الحديد والبقوليات 3-4 أيام" },
  { id: 189, name: "مضاد التخثر الذئبي (Lupus Anticoagulant) - Lupus Anticoagulant", category: "others", specimen: "Citrated Plasma", time: "1 يوم", price: 250, conditions: "" },
  { id: 190, name: "فيبرينوجين (Fibrinogen) - Fibrinogen", category: "others", specimen: "Citrated Plasma", time: "1 يوم", price: 160, conditions: "" },
  { id: 191, name: "منتجات تحلل الفيبرين (Fibrinogen degradation products (FDP)) - Fibrin Degradation Products", category: "others", specimen: "Citrated Plasma", time: "1 يوم", price: 250, conditions: "" },
  { id: 192, name: "حساسية الطعام (Food Print) - Food Allergy Panel", category: "others", specimen: "", time: "", price: 2000, conditions: "بعد الخصم 1600 LE" },
  { id: 193, name: "حساسية الاستنشاق (IgE Specific (Inhalant allergens) RAST) - Inhalant Allergy Panel", category: "others", specimen: "", time: "", price: 2000, conditions: "بعد الخصم 1600 LE" },
  { id: 194, name: "فحص جين الحمى المتوسطية العائلية (FMF (PCR for Familial Mediterranean Fever Gene Mutation)) - Familial Mediterranean Fever Gene Mutation", category: "others", specimen: "EDTA", time: "7-8 أيام", price: 1600, conditions: "" },
  { id: 195, name: "أجسام مضادة للكبد والكلى (LKM-Ab (Liver kidney microsomal ab)) - Liver Kidney Microsomal Antibodies", category: "others", specimen: "", time: "", price: 550, conditions: "" },
  { id: 196, name: "أجسام مضادة للمستضدات النووية المستخلصة (ENA (Extractable nuclear Antigens autoantibodies)) - Extractable Nuclear Antigens Antibodies", category: "others", specimen: "", time: "", price: 850, conditions: "" },
  { id: 197, name: "اختبار كوانتيفيرون للسل (TB Gold (QuantiFERON)) - QuantiFERON-TB Gold", category: "others", specimen: "Heparin", time: "3-4 أيام", price: 1700, conditions: "" },
  { id: 198, name: "بروتين أميلويد أ (Amyloid A protein) - Amyloid A Protein", category: "others", specimen: "", time: "", price: 400, conditions: "" }
 ];

    const testsContainer = document.getElementById('testsContainer');
    const searchInput = document.getElementById('searchInput');
    const categoryBtns = document.querySelectorAll('.category-btn');
    const cartIcon = document.getElementById('cartIcon');
    const cartModal = document.getElementById('cartModal');
    const closeCart = document.getElementById('closeCart');
    const overlay = document.getElementById('overlay');
    const cartItems = document.getElementById('cartItems');
    const cartSummary = document.getElementById('cartSummary');
    const cartTotal = document.getElementById('cartTotal');
    const cartCount = document.getElementById('cartCount');
    const toast = document.getElementById('toast');
